name: bash-shell-inline

on:
  workflow_dispatch:
    inputs:
      machines:
        description: 'GitHub virtual environments (`ubuntu-latest`, `windows-latest`, ...)'
        default: 'ubuntu-latest, windows-latest, macos-latest'
        required: false

jobs:
  setup-matrix:
    runs-on: ubuntu-latest

    outputs:
      matrix: ${{ steps.setup-matrix.outputs.matrix }}

    steps:
      - name: Setup matrix
        id: setup-matrix
        run: |
          MACHINES=$(echo "\"${{ github.event.inputs.machines }}\"" | tr -d '[:space:]' | sed 's/,/", "/g')
          echo $MACHINES
          echo "::set-output name=matrix::{\"os\": [$MACHINES]}"

  matrix-consumer:
    runs-on: ubuntu-latest

    needs: setup-matrix

    steps:
      - run: echo "${{needs.setup-matrix.outputs.matrix}}"
