name: github-echo-outputs-environment-variables

on:
  workflow_dispatch:

env:
  KEY_ONE: env one
  KEY_TWO: env two

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - name: Set output
        id: step
        run: |
          echo "key_1=value 1" >> "$GITHUB_OUTPUT"
          echo "key_2=value 2" >> "$GITHUB_OUTPUT"

      - name: Echo variables
        shell: kotlin -howtorun .main.kts {0}
        run: |
          import java.io.File
          
          println(System.getenv("GITHUB_ENV"))
          println("GitHub environment variables json:")
          println(File(System.getenv("GITHUB_ENV")).readText())
          println(System.getenv("GITHUB_OUTPUT"))
          println("GitHub outputs json:")
          println(File(System.getenv("GITHUB_OUTPUT")).readText())
