name: kotlin-shell

on:
  workflow_dispatch:
    inputs:
      args:
        description: 'Arguments, sample `"hi"` or `"arg1" "arg2"`'
        default: ''
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Kotlin code
        run: kotlin .github/workflows/kotlin-shell.main.kts ${{ github.event.inputs.args }}
