name: needs-control-flow

on:
  workflow_dispatch:
    inputs:
      value:
        description: 'Tag prefix'
        required: true
        default: 'a'
        type: choice
        options:
          - 'a'
          - 'b'

jobs:
  job1:
    runs-on: ubuntu-latest

    outputs:
      output1: ${{ steps.step.outputs.test }}

    steps:
      - name: Set output
        id: step
        run: echo "test=${{ github.event.inputs.value }}" >> "$GITHUB_OUTPUT"

  job2:
    runs-on: ubuntu-latest

    needs: [job1]

    if: needs.job1.outputs.output1 == 'a'

    steps:
      - name: Job2 echo
        run: echo "Job 2 called with the output ${{ needs.job1.outputs.output1 }}"
